name: Release Test

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      targetSha:
        description: 'The target SHA to run tests on'
        required: true
      testSha:
        description: 'The commit SHA to test'
        required: true

jobs:
  run-on-dispatch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: dapr-test/dapr
          ref: ${{ inputs.targetSha }}

      - name: Update commit status
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/dapr-test/dapr/statuses/${{ inputs.targetSha }}\
            -f "state=success" -f "description=The build succeeded!" -f "context=release/test/${{ inputs.testSha }}"
